// Mocks generated by Mockito 5.3.2 from annotations
// in leehs_brandi/test/models.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:leehs_brandi/models/kakao_image_search_request.dart' as _i2;
import 'package:leehs_brandi/models/kakao_image_search_response.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$KakaoImageSearchRequestCopyWith_0<$Res> extends _i1.SmartFake
    implements _i2.$KakaoImageSearchRequestCopyWith<$Res> {
  _Fake$KakaoImageSearchRequestCopyWith_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$KakaoImageSearchResponseCopyWith_1<$Res> extends _i1.SmartFake
    implements _i3.$KakaoImageSearchResponseCopyWith<$Res> {
  _Fake$KakaoImageSearchResponseCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$KakaoImageSearchResponseMetaCopyWith_2<$Res> extends _i1.SmartFake
    implements _i3.$KakaoImageSearchResponseMetaCopyWith<$Res> {
  _Fake$KakaoImageSearchResponseMetaCopyWith_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$KakaoImageSearchResponseDocCopyWith_3<$Res> extends _i1.SmartFake
    implements _i3.$KakaoImageSearchResponseDocCopyWith<$Res> {
  _Fake$KakaoImageSearchResponseDocCopyWith_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KakaoImageSearchRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockKakaoImageSearchRequest extends _i1.Mock
    implements _i2.KakaoImageSearchRequest {
  @override
  String get query => (super.noSuchMethod(
        Invocation.getter(#query),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i2.$KakaoImageSearchRequestCopyWith<_i2.KakaoImageSearchRequest>
      get copyWith => (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$KakaoImageSearchRequestCopyWith_0<
                _i2.KakaoImageSearchRequest>(
              this,
              Invocation.getter(#copyWith),
            ),
            returnValueForMissingStub: _Fake$KakaoImageSearchRequestCopyWith_0<
                _i2.KakaoImageSearchRequest>(
              this,
              Invocation.getter(#copyWith),
            ),
          ) as _i2
              .$KakaoImageSearchRequestCopyWith<_i2.KakaoImageSearchRequest>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [KakaoImageSearchResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockKakaoImageSearchResponse extends _i1.Mock
    implements _i3.KakaoImageSearchResponse {
  @override
  List<_i3.KakaoImageSearchResponseDoc> get documents => (super.noSuchMethod(
        Invocation.getter(#documents),
        returnValue: <_i3.KakaoImageSearchResponseDoc>[],
        returnValueForMissingStub: <_i3.KakaoImageSearchResponseDoc>[],
      ) as List<_i3.KakaoImageSearchResponseDoc>);
  @override
  _i3.$KakaoImageSearchResponseCopyWith<_i3.KakaoImageSearchResponse>
      get copyWith => (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$KakaoImageSearchResponseCopyWith_1<
                _i3.KakaoImageSearchResponse>(
              this,
              Invocation.getter(#copyWith),
            ),
            returnValueForMissingStub: _Fake$KakaoImageSearchResponseCopyWith_1<
                _i3.KakaoImageSearchResponse>(
              this,
              Invocation.getter(#copyWith),
            ),
          ) as _i3
              .$KakaoImageSearchResponseCopyWith<_i3.KakaoImageSearchResponse>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [KakaoImageSearchResponseMeta].
///
/// See the documentation for Mockito's code generation for more information.
class MockKakaoImageSearchResponseMeta extends _i1.Mock
    implements _i3.KakaoImageSearchResponseMeta {
  @override
  int get totalCount => (super.noSuchMethod(
        Invocation.getter(#totalCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  int get pageableCount => (super.noSuchMethod(
        Invocation.getter(#pageableCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  bool get isEnd => (super.noSuchMethod(
        Invocation.getter(#isEnd),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i3.$KakaoImageSearchResponseMetaCopyWith<_i3.KakaoImageSearchResponseMeta>
      get copyWith => (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$KakaoImageSearchResponseMetaCopyWith_2<
                _i3.KakaoImageSearchResponseMeta>(
              this,
              Invocation.getter(#copyWith),
            ),
            returnValueForMissingStub:
                _Fake$KakaoImageSearchResponseMetaCopyWith_2<
                    _i3.KakaoImageSearchResponseMeta>(
              this,
              Invocation.getter(#copyWith),
            ),
          ) as _i3.$KakaoImageSearchResponseMetaCopyWith<
              _i3.KakaoImageSearchResponseMeta>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [KakaoImageSearchResponseDoc].
///
/// See the documentation for Mockito's code generation for more information.
class MockKakaoImageSearchResponseDoc extends _i1.Mock
    implements _i3.KakaoImageSearchResponseDoc {
  @override
  String get collection => (super.noSuchMethod(
        Invocation.getter(#collection),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get thumbnailUrl => (super.noSuchMethod(
        Invocation.getter(#thumbnailUrl),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get imageUrl => (super.noSuchMethod(
        Invocation.getter(#imageUrl),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  int get width => (super.noSuchMethod(
        Invocation.getter(#width),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  int get height => (super.noSuchMethod(
        Invocation.getter(#height),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
  @override
  String get displaySitename => (super.noSuchMethod(
        Invocation.getter(#displaySitename),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get docUrl => (super.noSuchMethod(
        Invocation.getter(#docUrl),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.$KakaoImageSearchResponseDocCopyWith<_i3.KakaoImageSearchResponseDoc>
      get copyWith => (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$KakaoImageSearchResponseDocCopyWith_3<
                _i3.KakaoImageSearchResponseDoc>(
              this,
              Invocation.getter(#copyWith),
            ),
            returnValueForMissingStub:
                _Fake$KakaoImageSearchResponseDocCopyWith_3<
                    _i3.KakaoImageSearchResponseDoc>(
              this,
              Invocation.getter(#copyWith),
            ),
          ) as _i3.$KakaoImageSearchResponseDocCopyWith<
              _i3.KakaoImageSearchResponseDoc>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
